services:
  db-2:
    image: mariadb:11.4
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${GENERAL_PASSWORD}
      MARIADB_DATABASE: subscription-service
      MARIADB_ALLOW_EMPTY_PASSWORD: "no"
    ports:
      - "3307:3306"
    volumes:
      - mariadb2_data:/var/lib/mysql
    networks:
      - subscription-network

  subscription-service:
    build: .
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db-2:3306/subscription-service?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: ${GENERAL_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${GENERAL_PASSWORD}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.mariadb.jdbc.Driver
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MariaDBDialect
    depends_on:
      - db-2
    networks:
      - subscription-network

volumes:
  mariadb2_data:

networks:
  subscription-network:
    external: true
    name: user-service_main-network